"""JavaScript 目标转译器.

将 IR 转换为可以在 Node.js / 浏览器中运行的 JavaScript 代码.
"""

from src.core.processing_layer.ir_transpiler import (
    AbstractTranspiler,
    IROutput,
    TargetLanguage,
)


class JavaScriptTarget:
    """JavaScript 转译入口.

    使用示例:
        >>> target = JavaScriptTarget()
        >>> output = target.compile("Hello World")
        >>> print(output.source_code)
        // Auto-generated by Super-HelloWorld IR Transpiler
        console.log("Hello World");
    """

    def __init__(self) -> None:
        from src.core.processing_layer.ir_transpiler import JavaScriptTranspiler
        self._transpiler: AbstractTranspiler = JavaScriptTranspiler()

    def compile(self, message: str = "Hello World") -> IROutput:
        """编译为 JavaScript."""
        from src.core.processing_layer.ir_transpiler import IRBuilder
        builder = IRBuilder()
        ir_tree = builder.build_custom(message) if message != "Hello World" else builder.build_hello_world()
        return self._transpiler.transpile(ir_tree)

    @property
    def target_language(self) -> TargetLanguage:
        return TargetLanguage.JAVASCRIPT
