"""IR 转译器 — 将 Hello World 转换为多语言中间表示.

支持的目标语言:
    - JavaScript (Node.js / Browser)
    - Java (JVM / Android)
    - C++ (GCC / Clang / MSVC)
    - Rust (Safe)
    - WASM (WebAssembly Text Format)

所有转译基于中间 IR 树，确保跨平台一致性。
"""

from __future__ import annotations

import contextlib
import json
import time
from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from enum import Enum
from typing import Any


class TargetLanguage(Enum):
    """目标语言枚举."""

    JAVASCRIPT = "javascript"
    JAVA = "java"
    CPP = "cpp"
    RUST = "rust"
    WASM = "wasm"
    PYTHON = "python"
    GO = "go"
    CSHARP = "csharp"


# ---- IR 数据结构 ----


@dataclass(frozen=True)
class IRNode:
    """IR 节点 (不可变)."""

    node_type: str  # program / statement / expression / literal
    value: str
    children: list[IRNode] = field(default_factory=list)
    metadata: dict[str, str] = field(default_factory=dict)


@dataclass(frozen=True)
class IROutput:
    """IR 输出结果."""

    target_language: TargetLanguage
    source_code: str
    ast_representation: dict[str, Any]
    source_map: dict[int, int]  # 源位置 → 目标位置
    encoding: str = "UTF-8"
    compiled_at: float = field(default_factory=time.time)


# ---- 抽象转译器 ----


class AbstractTranspiler(ABC):
    """转译器抽象基类."""

    @abstractmethod
    def transpile(self, ir_tree: IRNode) -> IROutput:
        """将 IR 树转译为源代码.

        Args:
            ir_tree: 中间表示树.

        Returns:
            包含目标源代码和元数据的 IROutput.
        """
        ...

    @abstractmethod
    def target_language(self) -> TargetLanguage:
        """返回目标语言."""
        ...

    def generate_source_map(self, source: str, target: str) -> dict[int, int]:
        """生成源映射."""
        return {i: i for i in range(min(len(source), len(target)))}


# ---- IR 树构建器 ----


class IRBuilder:
    """IR 树构建器 — 构建 Hello World 的标准化 IR 表示."""

    _HELLO_WORLD_MESSAGE: str = "Hello World"

    def build_hello_world(self) -> IRNode:
        """构建 Hello World 的 IR 表示.

        IR 结构:
            program
              └── statement (function_call: print)
                    └── literal: "Hello World"
        """
        literal = IRNode(
            node_type="literal",
            value=self._HELLO_WORLD_MESSAGE,
            metadata={"type": "string", "length": str(len(self._HELLO_WORLD_MESSAGE))},
        )
        statement = IRNode(
            node_type="statement",
            value="print",
            children=[literal],
            metadata={"function": "output", "side_effects": "true"},
        )
        program = IRNode(
            node_type="program",
            value="hello_world",
            children=[statement],
            metadata={"author": "Enterprise", "version": "1.0.0"},
        )
        return program

    def build_custom(self, message: str) -> IRNode:
        """构建自定义消息的 IR 表示.

        Args:
            message: 自定义消息.

        Returns:
            IR 树根节点.
        """
        literal = IRNode(
            node_type="literal",
            value=message,
            metadata={"type": "string", "length": str(len(message))},
        )
        statement = IRNode(
            node_type="statement",
            value="print",
            children=[literal],
        )
        return IRNode(
            node_type="program",
            value="custom_output",
            children=[statement],
        )


# ---- 具体转译器实现 ----


class JavaScriptTranspiler(AbstractTranspiler):
    """JavaScript 转译器."""

    def target_language(self) -> TargetLanguage:
        return TargetLanguage.JAVASCRIPT

    def transpile(self, ir_tree: IRNode) -> IROutput:
        """转译为 JS.

        输出:
            // Auto-generated by Super-HelloWorld IR Transpiler
            console.log("Hello World");
        """
        literal = (
            ir_tree.children[0].children[0].value
            if ir_tree.children and ir_tree.children[0].children
            else ""
        )
        code = f'// Auto-generated by Super-HelloWorld IR Transpiler\nconsole.log("{literal}");\n'
        return IROutput(
            target_language=TargetLanguage.JAVASCRIPT,
            source_code=code,
            ast_representation={
                "type": "Program",
                "body": [
                    {
                        "type": "ExpressionStatement",
                        "expression": {
                            "type": "CallExpression",
                            "callee": {
                                "type": "MemberExpression",
                                "object": "console",
                                "property": "log",
                            },
                            "arguments": [{"type": "Literal", "value": literal}],
                        },
                    }
                ],
            },
            source_map=self.generate_source_map(literal, code),
        )


class JavaTranspiler(AbstractTranspiler):
    """Java 转译器."""

    def target_language(self) -> TargetLanguage:
        return TargetLanguage.JAVA

    def transpile(self, ir_tree: IRNode) -> IROutput:
        """转译为 Java.

        输出:
            public class HelloWorld {
                public static void main(String[] args) {
                    System.out.println("Hello World");
                }
            }
        """
        literal = (
            ir_tree.children[0].children[0].value
            if ir_tree.children and ir_tree.children[0].children
            else ""
        )
        code = (
            "// Auto-generated by Super-HelloWorld IR Transpiler\n"
            "public class HelloWorld {\n"
            "    public static void main(String[] args) {\n"
            f'        System.out.println("{literal}");\n'
            "    }\n"
            "}\n"
        )
        return IROutput(
            target_language=TargetLanguage.JAVA,
            source_code=code,
            ast_representation={
                "type": "CompilationUnit",
                "types": [
                    {
                        "type": "ClassDeclaration",
                        "name": "HelloWorld",
                        "methods": [
                            {
                                "type": "MethodDeclaration",
                                "name": "main",
                                "body": [
                                    {
                                        "type": "MethodInvocation",
                                        "target": "System.out",
                                        "method": "println",
                                        "arguments": [literal],
                                    }
                                ],
                            }
                        ],
                    }
                ],
            },
            source_map=self.generate_source_map(literal, code),
        )


class CppTranspiler(AbstractTranspiler):
    """C++ 转译器."""

    def target_language(self) -> TargetLanguage:
        return TargetLanguage.CPP

    def transpile(self, ir_tree: IRNode) -> IROutput:
        """转译为 C++.

        输出:
            #include <iostream>
            int main() {
                std::cout << "Hello World" << std::endl;
                return 0;
            }
        """
        literal = (
            ir_tree.children[0].children[0].value
            if ir_tree.children and ir_tree.children[0].children
            else ""
        )
        code = (
            "// Auto-generated by Super-HelloWorld IR Transpiler\n"
            "#include <iostream>\n"
            "\n"
            "int main() {\n"
            f'    std::cout << "{literal}" << std::endl;\n'
            "    return 0;\n"
            "}\n"
        )
        return IROutput(
            target_language=TargetLanguage.CPP,
            source_code=code,
            ast_representation={
                "type": "TranslationUnit",
                "declarations": [
                    {
                        "type": "FunctionDecl",
                        "name": "main",
                        "body": [
                            {
                                "type": "ExprStmt",
                                "expr": {
                                    "type": "Operator<<",
                                    "left": {
                                        "type": "Operator<<",
                                        "left": "std::cout",
                                        "right": literal,
                                    },
                                    "right": "std::endl",
                                },
                            },
                            {"type": "ReturnStmt", "value": 0},
                        ],
                    }
                ],
            },
            source_map=self.generate_source_map(literal, code),
        )


class RustTranspiler(AbstractTranspiler):
    """Rust 转译器."""

    def target_language(self) -> TargetLanguage:
        return TargetLanguage.RUST

    def transpile(self, ir_tree: IRNode) -> IROutput:
        """转译为 Rust.

        输出:
            fn main() {
                println!("Hello World");
            }
        """
        literal = (
            ir_tree.children[0].children[0].value
            if ir_tree.children and ir_tree.children[0].children
            else ""
        )
        code = (
            "// Auto-generated by Super-HelloWorld IR Transpiler\n"
            "fn main() {\n"
            f'    println!("{literal}");\n'
            "}\n"
        )
        return IROutput(
            target_language=TargetLanguage.RUST,
            source_code=code,
            ast_representation={
                "type": "Crate",
                "items": [
                    {
                        "type": "Function",
                        "name": "main",
                        "body": {
                            "type": "Block",
                            "stmts": [
                                {"type": "MacroInvocation", "macro": "println", "args": [literal]}
                            ],
                        },
                    }
                ],
            },
            source_map=self.generate_source_map(literal, code),
        )


class WasmTranspiler(AbstractTranspiler):
    """WebAssembly 转译器 (WAT 格式)."""

    def target_language(self) -> TargetLanguage:
        return TargetLanguage.WASM

    def transpile(self, ir_tree: IRNode) -> IROutput:
        """转译为 WAT (WebAssembly Text Format).

        输出保存为 .wat 文件，可编译为 .wasm。
        """
        literal = (
            ir_tree.children[0].children[0].value
            if ir_tree.children and ir_tree.children[0].children
            else ""
        )
        code = (
            ";; Auto-generated by Super-HelloWorld IR Transpiler\n"
            "(module\n"
            '  (import "console" "log" (func $log (param i32 i32)))\n'
            '  (import "js" "mem" (memory 1))\n'
            f'  (data (i32.const 0) "{literal}")\n'
            '  (func (export "hello_world")\n'
            f"    (call $log\n"
            f"      (i32.const 0)\n"
            f"      (i32.const {len(literal)}))\n"
            "  )\n"
            ")\n"
        )
        return IROutput(
            target_language=TargetLanguage.WASM,
            source_code=code,
            ast_representation={
                "type": "Module",
                "imports": [{"module": "console", "name": "log"}],
                "exports": [{"name": "hello_world"}],
                "data": [{"offset": 0, "value": literal}],
            },
            source_map={},
        )


# ---- 转译器注册表 ----

_TRANSPILER_REGISTRY: dict[TargetLanguage, AbstractTranspiler] = {
    TargetLanguage.JAVASCRIPT: JavaScriptTranspiler(),
    TargetLanguage.JAVA: JavaTranspiler(),
    TargetLanguage.CPP: CppTranspiler(),
    TargetLanguage.RUST: RustTranspiler(),
    TargetLanguage.WASM: WasmTranspiler(),
}


class IRTranspiler:
    """IR 转译器 — 多语言中间表示转译入口.

    使用示例:
        >>> transpiler = IRTranspiler()
        >>> js_output = transpiler.transpile_to(TargetLanguage.JAVASCRIPT)
        >>> print(js_output.source_code)
        // Auto-generated by Super-HelloWorld IR Transpiler
        console.log("Hello World");

        >>> all_outputs = transpiler.transpile_all()
        >>> for lang, output in all_outputs.items():
        ...     print(f"{lang.value}: {len(output.source_code)} chars")
    """

    def __init__(self) -> None:
        """初始化 IR 转译器."""
        self._builder: IRBuilder = IRBuilder()
        self._message: str = "Hello World"
        self._transpile_count: int = 0

    # ---- 公共 API ----

    def transpile_to(self, target: TargetLanguage, message: str | None = None) -> IROutput:
        """转译为指定语言.

        Args:
            target: 目标语言.
            message: 自定义消息 (默认 Hello World).

        Returns:
            IROutput 对象.

        Raises:
            ValueError: 不支持的目标语言.
        """
        transpiler = _TRANSPILER_REGISTRY.get(target)
        if transpiler is None:
            raise ValueError(f"Unsupported target language: {target}")

        msg = message or self._message
        ir_tree = self._builder.build_custom(msg) if message else self._builder.build_hello_world()
        output = transpiler.transpile(ir_tree)
        self._transpile_count += 1
        return output

    def transpile_all(self, message: str | None = None) -> dict[TargetLanguage, IROutput]:
        """转译为所有支持的语言.

        Args:
            message: 自定义消息.

        Returns:
            {语言: IROutput} 映射.
        """
        results: dict[TargetLanguage, IROutput] = {}
        for lang in TargetLanguage:
            with contextlib.suppress(ValueError):
                results[lang] = self.transpile_to(lang, message)
        return results

    def get_ir_tree(self, message: str | None = None) -> IRNode:
        """获取 IR 树 (不进行转译).

        Args:
            message: 自定义消息.

        Returns:
            IR 树根节点.
        """
        if message:
            return self._builder.build_custom(message)
        return self._builder.build_hello_world()

    def export_ir_json(self, message: str | None = None) -> str:
        """导出 IR 树为 JSON.

        Args:
            message: 自定义消息.

        Returns:
            JSON 字符串.
        """
        ir_tree = self.get_ir_tree(message)
        return json.dumps(
            self._serialize_ir(ir_tree),
            indent=2,
            ensure_ascii=False,
        )

    def export_all_to_files(self, output_dir: str = "./output") -> dict[TargetLanguage, str]:
        """将所有转译结果导出到文件.

        需要在实际文件系统中运行时使用。

        Args:
            output_dir: 输出目录.

        Returns:
            {语言: 文件路径} 映射.
        """
        import os

        os.makedirs(output_dir, exist_ok=True)
        ext_map = {
            TargetLanguage.JAVASCRIPT: ".js",
            TargetLanguage.JAVA: ".java",
            TargetLanguage.CPP: ".cpp",
            TargetLanguage.RUST: ".rs",
            TargetLanguage.WASM: ".wat",
            TargetLanguage.PYTHON: ".py",
            TargetLanguage.GO: ".go",
            TargetLanguage.CSHARP: ".cs",
        }

        results: dict[TargetLanguage, str] = {}
        outputs = self.transpile_all()

        for lang, output in outputs.items():
            ext = ext_map.get(lang, ".txt")
            filename = f"hello_world{ext}"
            filepath = os.path.join(output_dir, filename)
            with open(filepath, "w", encoding="utf-8") as f:
                f.write(output.source_code)
            results[lang] = filepath

        return results

    # ---- 内部 ----

    @staticmethod
    def _serialize_ir(node: IRNode) -> dict[str, Any]:
        """递归序列化 IR 树."""
        return {
            "node_type": node.node_type,
            "value": node.value,
            "metadata": node.metadata,
            "children": [IRTranspiler._serialize_ir(child) for child in node.children],
        }

    # ---- 属性 ----

    @property
    def message(self) -> str:
        """当前消息."""
        return self._message

    @message.setter
    def message(self, value: str) -> None:
        self._message = value

    @property
    def transpile_count(self) -> int:
        """转译次数."""
        return self._transpile_count

    @property
    def supported_languages(self) -> list[TargetLanguage]:
        """支持的目标语言列表."""
        return list(_TRANSPILER_REGISTRY.keys())

    @classmethod
    def register_transpiler(
        cls,
        language: TargetLanguage,
        transpiler: AbstractTranspiler,
    ) -> None:
        """注册自定义转译器.

        Args:
            language: 目标语言.
            transpiler: 转译器实例.
        """
        _TRANSPILER_REGISTRY[language] = transpiler
